[general]
static=yes
writeprotect=no

[default]
exten => _X.,1,Answer()
same => n,AGI(agi://localhost:4573/ai-agent)
same => n,Hangup()

[ai-incoming]
exten => s,1,Answer()
same => n,AGI(agi://localhost:4573/ai-agent)
same => n,Hangup()
